deploy:
  - provider: NuGet
    server: https://nuget.pkg.github.com/mrsalty/index.json
    artifact: /.nupkg/
    username: mrsalty
    api_key:
      secure: zK+6ab7J5ospEKwXQ5Cd2PYGOTro+KKWYnyKinEO8DsmnmJr977ClTGVnBbZ4Zxd
    skip_symbols: false
    artifact: /.*\.nupkg/

    version: '{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off